#开发环境
fileupload:
  upload:
    dir: F:\webuploader-dir\
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 1024

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: 1000
        min-idle: 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
